CREATE SCHEMA IF NOT EXISTS houston_311 AUTHORIZATION postgres;

CREATE TABLE houston_311.incidents (
    case_365_number TEXT,
    case_number TEXT,
    incident_address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status TEXT,
    created_date_local TIMESTAMP,
    closed_date TIMESTAMP,
    title TEXT,
    incident_case_type TEXT,
    sla_time INTERVAL,
    resolve_by_time TIMESTAMP,
    service_area TEXT,
    council_district TEXT,
    key_map TEXT,
    department TEXT,
    division TEXT,
    ava_case_type TEXT,
    state_code TEXT,
    state_code_name TEXT,
    sla_start_time TIMESTAMP,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    incident_street TEXT,
    incident_city TEXT,
    incident_state TEXT,
    zip_code TEXT,
    taxid TEXT,
    created_date_utc TIMESTAMP,
    customer_super_neighborhood TEXT,
    management_district TEXT,
    garbage_route TEXT,
    garbage_day TEXT,
    swm_quadrant TEXT,
    recycling_route TEXT,
    recycling_day TEXT,
    recycling_quadrant TEXT,
    recycling_areas TEXT,
    heavy_trash_day TEXT,
    heavy_trash_quadrant TEXT,
    queue TEXT,
    etj TEXT,
    sla_name TEXT,
    channel TEXT,
    extract_date TIMESTAMP,
    latest_case_notes TEXT,
    sample_case_conflicts_notes TEXT,
    description TEXT,
    resolution_notes TEXT,
    PRIMARY KEY (case_number)
);